version: '3'

services:
  vpn:
    container_name: vpn
    image: docker-openconnect-vpn:1.0.1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/.Xauthority:/.Xauthority
      - $PWD:/hostroot
    environment:
      - OUTSIDE_HOSTNAME=${OUTSIDE_HOSTNAME}
      - DOCKER_BRIDGE_ADDRESS=${DOCKER_BRIDGE_ADDRESS}
      - HEALTHCHECK_HOST=${HEALTHCHECK_HOST}
      - VPN_ENDPOINT=${VPN_ENDPOINT}
      - ADDITIONAL_VPN_ARGS=${ADDITIONAL_VPN_ARGS}
      - ADDITIONAL_COMMANDS=${ADDITIONAL_COMMANDS}
      - DISPLAY=${DISPLAY}
      - XAUTH=/.Xauthority
      - XAUTHORITY=/.Xauthority
    networks:
      vpn_network:
        ipv4_address: 172.32.0.200
    privileged: true
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
    restart: "no"
    security_opt:
      - label:disable

networks:
  vpn_network:
    ipam:
      driver: default
      config:
        - subnet: 172.32.0.0/24
