version: '3'

services:
  vpn:
    container_name: vpn
    image: docker-openconnect-vpn:1.0.1
    environment:
      - VPN_COOKIE=${COOKIE}
      - VPN_USER=${VPN_USER}
      - VPN_OS=${VPN_OS}
      - VPN_ENDPOINT=${VPN_ENDPOINT}
      - ADDITIONAL_COMMANDS=${ADDITIONAL_COMMANDS}
    networks:
      vpn_network:
        ipv4_address: 172.32.0.200
    privileged: true
    cap_add:
      - NET_ADMIN
    restart: "no"
    security_opt:
      - label:disable

networks:
  vpn_network:
    ipam:
      driver: default
      config:
        - subnet: 172.32.0.0/24
